# Generated by Django 4.0.3 on 2022-04-02 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voltage_r', models.CharField(max_length=10)),
                ('voltage_y', models.CharField(max_length=10)),
                ('voltage_b', models.CharField(max_length=10)),
                ('current_r', models.CharField(max_length=10)),
                ('current_y', models.CharField(max_length=10)),
                ('current_b', models.CharField(max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Parameters',
                'ordering': ('-created',),
            },
        ),
    ]
