# Generated by Django 4.0.3 on 2022-04-09 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='error',
            field=models.BooleanField(default=False),
        ),
    ]
