# Generated by Django 4.0.3 on 2022-04-09 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_parameter_error'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameter',
            name='error',
        ),
    ]
